version: '3.8'
services:
  authentication-database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5000:5432'
    volumes:
      - authentication-database:/var/lib/postgresql/data

  user-database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5001:5432'
    volumes:
      - authentication-database:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      context: Frontend/web-react
      dockerfile: ./Dockerfile
    ports:
      - 3000:80

volumes:
  authentication-database:
  users-database: