version: '3.8'

services:
  authentication-database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5000"
    ports:
      - '5000:5432'
    volumes:
      - authentication-database:/var/lib/postgresql/data

  user-database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5001:5432'
    volumes:
      - user-database:/var/lib/postgresql/data # Fixed the volume name here

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672" # management UI
      - "5672:5672"   # default RabbitMQ broker port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  nginx:
    image:

volumes:
  authentication-database:
  user-database: # Fixed the volume name here
