# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available) to the container
COPY package*.json ./

# Install project dependencies inside the container
RUN npm install

# Copy the local src directory to the container
COPY . .

# Specify the command to run on container start in development mode
CMD ["npm", "start"]
